### ISSUE TITLE
可以公开代码嘛

### ISSUE THREAD

**Issue by dangshi** [Xuekai-Zhu/Original-image-assisted-tamper-detection#2]
想学习一下源码

**Comment by Xuekai-Zhu** [comment]
很好高兴您对我们的代码感兴趣！
由于代码我们需要整理成论文，论文目前还在撰写中，代码估计会在三月份开源！
天池论坛帖子中已经大致阐述了我们的思想，如果对具体实现细节有什么问题的话，欢迎致信 xuekaizhu@whu.edu.cn
